[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/server"
  bin = "tmp\\main.exe"
  entrypoint = ["tmp\\main.exe"]

  [build.windows]
    cmd = "go build -o ./tmp/main.exe ./cmd/server"
    bin = "tmp\\main.exe"
    entrypoint = ["tmp\\main.exe"]