name: Go CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.3"

      - name: Run tests
        run: go test ./...

      - name: Test SSH connection to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{secrets.EC2_USER }}
          key: ${{secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Connected to EC2 successfully!"
            hostname
            whoami
